### ISSUE TITLE
Pinning/simplifying environment file

### ISSUE THREAD

**Issue by Sparrow0hawk** [ARCTraining/swd6_hpp#22]
The environment file for this course is complex and on some systems can take a long time to solve and install (way too long).

This issue would look at simplifying or pinning dependencies in the environment.yml.

## Tasks
- [ ] - Identify core packages required
- [ ] - Identify pinned versions that should be added
- [ ] - Remove any unnecessary packages
